[package]
authors = ["Jan Keith Darunday <jkcdarunday@gmail.com>"]
name = "actix-web-boilerplate"
version = "0.1.0"

[dependencies]
actix = "0.7"
actix-web = "0.7"
futures = "0.1"
r2d2 = "0.8"
r2d2-diesel = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.diesel]
features = ["postgres"]
version = "1.3"
