version: '3'
services:
  database:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=qazwsx123
    - POSTGRES_DB=canduma
    command: postgres -c 'max_connections=200'
    volumes:
      - ./mydb:/var/lib/postgresql/data/
volumes:
  mydb: 