version: "3"
services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=qazwsx123
      - POSTGRES_USER=admin
      - POSTGRES_DB=actix_test
    volumes:
      - ./mydb:/var/lib/postgresql/data
volumes:
    mydb: